### ISSUE TITLE
Extra model path not working

### ISSUE THREAD

**Issue by alexisrolland** [ltdrdata/ComfyUI-Impact-Subpack#31]
Hello,

I have tried the following technics described in the README to add ultralytics extra model path, and it does not seem to be working. Here is the config I have used. Could you please tell me what I am doing wrong?

# First test = KO

```yml
comfyui:
    ultralytics: models\ultralytics\
```

# Second test = KO

```yml
comfyui:
    ultralytics: ultralytics\
```

# Third test = KO

```yml
comfyui:
    ultralytics_bbox: models\ultralytics_bbox\
    ultralytics_segm: models\ultralytics_segm\
```

Thanks
